refactor the scripts for rendering samples
synfig/synfig-tests-regressions pull request #13
Opened 2018-11-02 19:51 UTC by reSHARMA

Hello,

Sorry for the delayed response I was traveling, but I found  time to rethink about the whole code.
This pr is still under development, and test.sh is my copy of render.sh which I run on my system to debug.

At the end test.sh will get merged to render.sh

This would solve both the open issues :)

Thanks

2018-11-02 19:54 UTC, reSHARMA commented
So, the default-version is gone. Say we want to freeze version x for dir abc then just add a file abc.txt in it :)

2018-11-05 06:56 UTC, morevnaproject commented
Great, thank you! I have made a quick review - please check. ^__^

2018-11-05 11:48 UTC, reSHARMA commented
> I have made a quick review - please check. ^__^

I guess i'm missing something, where should I look for review :)

Another issue would be that circle.txt would be the version for whole circle dir and also for circle.sif, so it is better to change the default name of sample to circle-default.sif or anything that you may suggest.

2018-11-05 12:03 UTC, morevnaproject requested changes

2018-11-05 12:03 UTC, morevnaproject commented on render.sh
> +		wget --quiet $LINK -O "/tmp/synfig-$VERSION.appimage"
Please make sure to include changes from this commit - 37a89a05cf68d9c710ccea44c809742b489e9bdf

2018-11-05 12:03 UTC, morevnaproject commented on render.sh
> +	elif [ $PARSED_VERSION -eq 131020181026 ]; then
Please make sure to update version as here  ^__^ - 852146c077e6931b18235aec7d83c52b32834faf

2018-11-05 12:03 UTC, morevnaproject commented on render.sh
> +	if [ ! -d "/tmp/synfig-$VERSION.appimage" ]; then
A quick fix - 1e223b9f8cd6e5e6bcbe4cc85ce8f18a609609e9

2018-11-05 12:03 UTC, morevnaproject commented on render.sh
> +	if [ $(echo $NAME | grep -i '-') ]; then
Clever! But that disallows to use "-" in directory names. ^_^ Someone (like me) can forget about that restriction someday. ^__^ So I am proposing something like this (not tested):

```
if [ "$EXT" = "sif" ]; then
   render-only-one-file $file
else [ "$EXT" = "txt"]; then
   PARENT_DIR_NAME=${DIR##*/}
   if [ "$PARENT_DIR_NAME" = "$NAME" ]; then
      render-only-one-dir $file
   else
      render-only-one-dir $file
   fi
fi
```

2018-11-05 12:03 UTC, morevnaproject commented on render.sh
> +CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`
I suggest to  add possibility to run the script locally, outside of Travis. All we need to do is to replace this line with the code like this (not tested):

```
if [ -z "$TRAVIS_BUILD_DIR" ]; then
   TRAVIS_BUILD_DIR=$(cd `dirname "$0"`; pwd) # gets directory of current script
fi
cd "$TRAVIS_BUILD_DIR"
if [ -z "$TRAVIS_COMMIT_RANGE" ]; then
   # rebuild everything
   CHANGED_FILES="sources/sources.txt"
else
   CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`
fi
```

2018-11-05 12:10 UTC, morevnaproject commented
> I guess i'm missing something, where should I look for review :)

Oh, sorry, I forgot to press "Submit review" button. Should be here (above) now.

> Another issue would be that circle.txt would be the version for whole circle dir and also for circle.sif, so it is better to change the default name of sample to circle-default.sif or anything that you may suggest.

Good catch! Fixed now - dd79af7a2b9097d783cb6eb827a14450f32ecfdb

2018-11-05 13:02 UTC, reSHARMA commented on render.sh
> +	if [ $(echo $NAME | grep -i '-') ]; then
Thanks for the review, I've added everything else and it is looking good and will add this one after testing :)

2018-11-05 13:19 UTC, reSHARMA commented on render.sh
> +	if [ $(echo $NAME | grep -i '-') ]; then
Awesome observation :)

2018-11-05 13:37 UTC, reSHARMA commented
I think we are good to go :)

2018-11-05 16:55 UTC, merged

2018-11-05 16:59 UTC, morevnaproject commented
Awesome, thank you! I have merged the changes and It seems to successfully parsed by Travis! - https://travis-ci.org/synfig/synfig-tests-regressions/builds/450962444 ^__^

I think we can consider this task done. ^__^